// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTutoria2022_2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220730224301_primera")]
    partial class primera
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("ApiTutoria2022_2.Models.Carrera", b =>
                {
                    b.Property<int>("CarreraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DirectorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FacultadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CarreraId");

                    b.ToTable("Carreras");

                    b.HasData(
                        new
                        {
                            CarreraId = 12,
                            DirectorId = 103,
                            FacultadId = 12,
                            Nombre = "Ingeniero en Sistemas y Computación"
                        });
                });

            modelBuilder.Entity("ApiTutoria2022_2.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("BalancePendiente")
                        .HasColumnType("REAL");

                    b.Property<float>("BalanceTotal")
                        .HasColumnType("REAL");

                    b.Property<int>("CarreraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            EstudianteId = 2,
                            BalancePendiente = 0f,
                            BalanceTotal = 0f,
                            CarreraId = 12,
                            Matricula = "2016-0037",
                            PersonaId = 2
                        },
                        new
                        {
                            EstudianteId = 3,
                            BalancePendiente = 0f,
                            BalanceTotal = 0f,
                            CarreraId = 12,
                            Matricula = "2016-0037",
                            PersonaId = 3
                        },
                        new
                        {
                            EstudianteId = 1,
                            BalancePendiente = 0f,
                            BalanceTotal = 0f,
                            CarreraId = 12,
                            Matricula = "2016-0037",
                            PersonaId = 1
                        });
                });

            modelBuilder.Entity("ApiTutoria2022_2.Models.Horario", b =>
                {
                    b.Property<int>("HorariosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoraFin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeccionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HorariosId");

                    b.ToTable("Horarios");

                    b.HasData(
                        new
                        {
                            HorariosId = 200,
                            Aula = "LAB. DE INFORMATICA A",
                            Dia = "Tuesday",
                            HoraFin = "21:00",
                            HoraInicio = "18:00",
                            SeccionId = 200
                        },
                        new
                        {
                            HorariosId = 201,
                            Aula = "LAB. DE INFORMATICA B",
                            Dia = "Tuesday",
                            HoraFin = "21:00",
                            HoraInicio = "18:00",
                            SeccionId = 201
                        },
                        new
                        {
                            HorariosId = 202,
                            Aula = "LAB. DE INFORMATICA A",
                            Dia = "Monday",
                            HoraFin = "14:00",
                            HoraInicio = "12:00",
                            SeccionId = 202
                        },
                        new
                        {
                            HorariosId = 203,
                            Aula = "LAB. DE INFORMATICA A",
                            Dia = "Tuesday",
                            HoraFin = "14:00",
                            HoraInicio = "12:00",
                            SeccionId = 203
                        },
                        new
                        {
                            HorariosId = 204,
                            Aula = "LAB. DE INFORMATICA C",
                            Dia = "Monday",
                            HoraFin = "21:00",
                            HoraInicio = "18:00",
                            SeccionId = 204
                        },
                        new
                        {
                            HorariosId = 205,
                            Aula = "LAB. DE INFORMATICA A",
                            Dia = "Thursday",
                            HoraFin = "14:00",
                            HoraInicio = "12:00",
                            SeccionId = 205
                        },
                        new
                        {
                            HorariosId = 206,
                            Aula = "LAB. DE INFORMATICA A",
                            Dia = "Friday",
                            HoraFin = "14:00",
                            HoraInicio = "12:00",
                            SeccionId = 206
                        },
                        new
                        {
                            HorariosId = 207,
                            Aula = "LAB. DE INFORMATICA A",
                            Dia = "Monday",
                            HoraFin = "14:00",
                            HoraInicio = "12:00",
                            SeccionId = 207
                        },
                        new
                        {
                            HorariosId = 208,
                            Aula = "LAB. DE INFORMATICA A",
                            Dia = "Saturday",
                            HoraFin = "14:00",
                            HoraInicio = "12:00",
                            SeccionId = 208
                        },
                        new
                        {
                            HorariosId = 209,
                            Aula = "LAB. DE INFORMATICA A",
                            Dia = "Wednesday",
                            HoraFin = "14:00",
                            HoraInicio = "12:00",
                            SeccionId = 209
                        });
                });

            modelBuilder.Entity("ApiTutoria2022_2.Models.Inscripcion", b =>
                {
                    b.Property<int>("InscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFinalTrimestre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicioTrimestre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistrada")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UltimaInscripcion")
                        .HasColumnType("INTEGER");

                    b.HasKey("InscripcionId");

                    b.ToTable("Inscripciones");

                    b.HasData(
                        new
                        {
                            InscripcionId = 104,
                            EstudianteId = 1,
                            FechaFinalTrimestre = new DateTime(2022, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicioTrimestre = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRegistrada = new DateTime(2022, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UltimaInscripcion = true
                        },
                        new
                        {
                            InscripcionId = 105,
                            EstudianteId = 2,
                            FechaFinalTrimestre = new DateTime(2022, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicioTrimestre = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRegistrada = new DateTime(2022, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UltimaInscripcion = true
                        },
                        new
                        {
                            InscripcionId = 106,
                            EstudianteId = 3,
                            FechaFinalTrimestre = new DateTime(2022, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicioTrimestre = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRegistrada = new DateTime(2022, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UltimaInscripcion = true
                        });
                });

            modelBuilder.Entity("ApiTutoria2022_2.Models.InscripcionDetalle", b =>
                {
                    b.Property<int>("InscripcionDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InscripcionDetalleId");

                    b.ToTable("InscripcionDetalles");

                    b.HasData(
                        new
                        {
                            InscripcionDetalleId = 90,
                            AsignaturaId = 20,
                            InscripcionId = 104
                        },
                        new
                        {
                            InscripcionDetalleId = 91,
                            AsignaturaId = 21,
                            InscripcionId = 104
                        },
                        new
                        {
                            InscripcionDetalleId = 92,
                            AsignaturaId = 22,
                            InscripcionId = 105
                        },
                        new
                        {
                            InscripcionDetalleId = 93,
                            AsignaturaId = 23,
                            InscripcionId = 105
                        },
                        new
                        {
                            InscripcionDetalleId = 94,
                            AsignaturaId = 23,
                            InscripcionId = 106
                        },
                        new
                        {
                            InscripcionDetalleId = 95,
                            AsignaturaId = 24,
                            InscripcionId = 106
                        },
                        new
                        {
                            InscripcionDetalleId = 96,
                            AsignaturaId = 25,
                            InscripcionId = 106
                        },
                        new
                        {
                            InscripcionDetalleId = 97,
                            AsignaturaId = 26,
                            InscripcionId = 106
                        },
                        new
                        {
                            InscripcionDetalleId = 99,
                            AsignaturaId = 27,
                            InscripcionId = 106
                        },
                        new
                        {
                            InscripcionDetalleId = 100,
                            AsignaturaId = 28,
                            InscripcionId = 106
                        },
                        new
                        {
                            InscripcionDetalleId = 101,
                            AsignaturaId = 27,
                            InscripcionId = 104
                        },
                        new
                        {
                            InscripcionDetalleId = 102,
                            AsignaturaId = 28,
                            InscripcionId = 104
                        },
                        new
                        {
                            InscripcionDetalleId = 103,
                            AsignaturaId = 25,
                            InscripcionId = 105
                        },
                        new
                        {
                            InscripcionDetalleId = 104,
                            AsignaturaId = 26,
                            InscripcionId = 105
                        });
                });

            modelBuilder.Entity("ApiTutoria2022_2.Models.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginId");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            LoginId = 1,
                            EstudianteId = 2,
                            Password = "1234",
                            Usuario = "Jesus"
                        },
                        new
                        {
                            LoginId = 2,
                            EstudianteId = 3,
                            Password = "1234",
                            Usuario = "2016"
                        },
                        new
                        {
                            LoginId = 3,
                            EstudianteId = 1,
                            Password = "1234",
                            Usuario = "5"
                        });
                });

            modelBuilder.Entity("ApiTutoria2022_2.Models.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoInstitucion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoPersonal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DireccionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<char>("Sexo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tutor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            Apellidos = "Salazar",
                            Celular = "829-798-5996",
                            CorreoInstitucion = "enmanuel@klk.com",
                            CorreoPersonal = "",
                            DireccionId = 0,
                            FechaNacimiento = new DateTime(2022, 7, 30, 18, 43, 1, 550, DateTimeKind.Local).AddTicks(4526),
                            Nacionalidad = "Republica Dominicana",
                            Nombres = "Enmanuel",
                            NumeroCedula = "",
                            Sexo = 'N',
                            Telefono = "",
                            Tutor = "Ramon"
                        },
                        new
                        {
                            PersonaId = 2,
                            Apellidos = "Abreu",
                            Celular = "829-780-5880",
                            CorreoInstitucion = "jesus@klk.com",
                            CorreoPersonal = "",
                            DireccionId = 0,
                            FechaNacimiento = new DateTime(2022, 7, 30, 18, 43, 1, 550, DateTimeKind.Local).AddTicks(4548),
                            Nacionalidad = "Republica Dominicana",
                            Nombres = "Jesus",
                            NumeroCedula = "",
                            Sexo = 'N',
                            Telefono = "",
                            Tutor = "Jose"
                        },
                        new
                        {
                            PersonaId = 3,
                            Apellidos = "Peña Polonia",
                            Celular = "829-798-5826",
                            CorreoInstitucion = "Klk@klk.com",
                            CorreoPersonal = "",
                            DireccionId = 0,
                            FechaNacimiento = new DateTime(2022, 7, 30, 18, 43, 1, 550, DateTimeKind.Local).AddTicks(4562),
                            Nacionalidad = "Republica Dominicana",
                            Nombres = "Mario",
                            NumeroCedula = "",
                            Sexo = 'N',
                            Telefono = "",
                            Tutor = "RAMÓN FRANCISCO PEÑA GARCÍA"
                        });
                });

            modelBuilder.Entity("ApiTutoria2022_2.Models.Seccion", b =>
                {
                    b.Property<int>("SeccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeccionId");

                    b.ToTable("Secciones");

                    b.HasData(
                        new
                        {
                            SeccionId = 200,
                            AsignaturaId = 20,
                            DocenteId = 512
                        },
                        new
                        {
                            SeccionId = 201,
                            AsignaturaId = 21,
                            DocenteId = 512
                        },
                        new
                        {
                            SeccionId = 209,
                            AsignaturaId = 22,
                            DocenteId = 512
                        },
                        new
                        {
                            SeccionId = 202,
                            AsignaturaId = 23,
                            DocenteId = 1
                        },
                        new
                        {
                            SeccionId = 203,
                            AsignaturaId = 29,
                            DocenteId = 1
                        },
                        new
                        {
                            SeccionId = 204,
                            AsignaturaId = 24,
                            DocenteId = 1
                        },
                        new
                        {
                            SeccionId = 205,
                            AsignaturaId = 25,
                            DocenteId = 9
                        },
                        new
                        {
                            SeccionId = 206,
                            AsignaturaId = 26,
                            DocenteId = 9
                        },
                        new
                        {
                            SeccionId = 207,
                            AsignaturaId = 27,
                            DocenteId = 10
                        },
                        new
                        {
                            SeccionId = 208,
                            AsignaturaId = 28,
                            DocenteId = 10
                        });
                });

            modelBuilder.Entity("ApiTutoria2022_2.Models.Transaccion", b =>
                {
                    b.Property<int>("TransaccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Movimiento")
                        .HasColumnType("TEXT");

                    b.HasKey("TransaccionId");

                    b.ToTable("Transaccion");

                    b.HasData(
                        new
                        {
                            TransaccionId = 107,
                            Descripcion = "N/C DESCUENTO 50% ARTE Y CULTURA",
                            Estado = 5000m,
                            EstudianteId = 1,
                            FechaRegistro = new DateTime(2022, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = 5000m
                        },
                        new
                        {
                            TransaccionId = 117,
                            Descripcion = "PAGO RECIBIDO",
                            Estado = 10000m,
                            EstudianteId = 1,
                            FechaRegistro = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = 3000m
                        },
                        new
                        {
                            TransaccionId = 116,
                            Descripcion = "PAGO RECIBIDO",
                            Estado = 13000m,
                            EstudianteId = 1,
                            FechaRegistro = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = 5000m
                        },
                        new
                        {
                            TransaccionId = 115,
                            Descripcion = "INSCRIPCIÓN PERÍODO 1-2021",
                            Estado = 19000m,
                            EstudianteId = 1,
                            FechaRegistro = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = -18000m
                        },
                        new
                        {
                            TransaccionId = 114,
                            Descripcion = "PAGO RECIBIDO",
                            Estado = 1000m,
                            EstudianteId = 1,
                            FechaRegistro = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = 2000m
                        },
                        new
                        {
                            TransaccionId = 113,
                            Descripcion = "PAGO RECIBIDO",
                            Estado = 500m,
                            EstudianteId = 1,
                            FechaRegistro = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = 500m
                        },
                        new
                        {
                            TransaccionId = 103,
                            Descripcion = "INSCRIPCIÓN PERÍODO 3-2020",
                            Estado = 10000m,
                            EstudianteId = 1,
                            FechaRegistro = new DateTime(2020, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = -10000m
                        },
                        new
                        {
                            TransaccionId = 100,
                            Descripcion = "N/C DESCUENTO 50% ARTE Y CULTURA",
                            Estado = 0.0m,
                            EstudianteId = 1,
                            FechaRegistro = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = 5000m
                        },
                        new
                        {
                            TransaccionId = 101,
                            Descripcion = "PAGO RECIBIDO",
                            Estado = 5000m,
                            EstudianteId = 1,
                            FechaRegistro = new DateTime(2020, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = 10000m
                        },
                        new
                        {
                            TransaccionId = 105,
                            Descripcion = "INSCRIPCIÓN PERÍODO 1-2019",
                            Estado = 15000m,
                            EstudianteId = 1,
                            FechaRegistro = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = -15000m
                        },
                        new
                        {
                            TransaccionId = 104,
                            Descripcion = "N/C DESCUENTO 50% ARTE Y CULTURA",
                            Estado = 10000m,
                            EstudianteId = 2,
                            FechaRegistro = new DateTime(2022, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = 15000m
                        },
                        new
                        {
                            TransaccionId = 111,
                            Descripcion = "INSCRIPCIÓN PERÍODO 1-2019",
                            Estado = 25000m,
                            EstudianteId = 2,
                            FechaRegistro = new DateTime(2019, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = -15000m
                        },
                        new
                        {
                            TransaccionId = 112,
                            Descripcion = "N/C DESCUENTO 50% ARTE Y CULTURA",
                            Estado = 17000m,
                            EstudianteId = 2,
                            FechaRegistro = new DateTime(2019, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = 8000m
                        },
                        new
                        {
                            TransaccionId = 102,
                            Descripcion = "ABONO A CUENTA MEDIANTE DEPOSITO BR",
                            Estado = 4000m,
                            EstudianteId = 2,
                            FechaRegistro = new DateTime(2019, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = 13000m
                        },
                        new
                        {
                            TransaccionId = 106,
                            Descripcion = "N/C DESCUENTO 50% ARTE Y CULTURA",
                            Estado = 10000m,
                            EstudianteId = 3,
                            FechaRegistro = new DateTime(2019, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = 15000m
                        },
                        new
                        {
                            TransaccionId = 108,
                            Descripcion = "PAGO RECIBIDO",
                            Estado = 10000m,
                            EstudianteId = 3,
                            FechaRegistro = new DateTime(2022, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = 15000m
                        },
                        new
                        {
                            TransaccionId = 110,
                            Descripcion = "ABONO A CUENTA MEDIANTE DEPOSITO BR",
                            Estado = 10000m,
                            EstudianteId = 3,
                            FechaRegistro = new DateTime(2019, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Movimiento = 15000m
                        });
                });

            modelBuilder.Entity("Asignatura", b =>
                {
                    b.Property<int>("AsignaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarreraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Credito")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AsignaturaId");

                    b.ToTable("Asignaturas");

                    b.HasData(
                        new
                        {
                            AsignaturaId = 20,
                            CarreraId = 12,
                            Codigo = "ISC-101",
                            Credito = 2,
                            Nombre = "PROGRAMACION APLICADA II"
                        },
                        new
                        {
                            AsignaturaId = 21,
                            CarreraId = 12,
                            Codigo = "ISC-102",
                            Credito = 1,
                            Nombre = "LAB. PROGRAM. APLICADA II"
                        },
                        new
                        {
                            AsignaturaId = 22,
                            CarreraId = 12,
                            Codigo = "ISC-802",
                            Credito = 4,
                            Nombre = "DISEÑO DE SISTEMAS"
                        },
                        new
                        {
                            AsignaturaId = 29,
                            CarreraId = 12,
                            Codigo = "ISC-701",
                            Credito = 4,
                            Nombre = "SISTEMAS OPERATIVOS I"
                        },
                        new
                        {
                            AsignaturaId = 23,
                            CarreraId = 12,
                            Codigo = "ISC-701",
                            Credito = 4,
                            Nombre = "MERCADEO DE SOFTWARE"
                        },
                        new
                        {
                            AsignaturaId = 24,
                            CarreraId = 12,
                            Codigo = "ISC-702",
                            Credito = 4,
                            Nombre = "LABORATORIO SISTEMAS OPERATIVOS I"
                        },
                        new
                        {
                            AsignaturaId = 25,
                            CarreraId = 12,
                            Codigo = "ISC-704",
                            Credito = 4,
                            Nombre = "BASE DE DATOS"
                        },
                        new
                        {
                            AsignaturaId = 26,
                            CarreraId = 12,
                            Codigo = "ISC-703",
                            Credito = 4,
                            Nombre = "LAB. BASE DE DATOS "
                        },
                        new
                        {
                            AsignaturaId = 27,
                            CarreraId = 12,
                            Codigo = "ISC-705",
                            Credito = 4,
                            Nombre = "MATENIMIENTO DE HARDWARE"
                        },
                        new
                        {
                            AsignaturaId = 28,
                            CarreraId = 12,
                            Codigo = "CNT-213",
                            Credito = 4,
                            Nombre = "CONTABILIDAD GENERAL I "
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
