// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTutoria2022_2.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("ApiTutoria2022_2.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("BalancePendiente")
                        .HasColumnType("REAL");

                    b.Property<float>("BalanceTotal")
                        .HasColumnType("REAL");

                    b.Property<int>("CarreraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            EstudianteId = 1,
                            BalancePendiente = 0f,
                            BalanceTotal = 0f,
                            CarreraId = 2,
                            Matricula = "2016-0037",
                            PersonaId = 1
                        },
                        new
                        {
                            EstudianteId = 2,
                            BalancePendiente = 0f,
                            BalanceTotal = 0f,
                            CarreraId = 2,
                            Matricula = "2016-0037",
                            PersonaId = 2
                        },
                        new
                        {
                            EstudianteId = 3,
                            BalancePendiente = 0f,
                            BalanceTotal = 0f,
                            CarreraId = 2,
                            Matricula = "2016-0037",
                            PersonaId = 3
                        });
                });

            modelBuilder.Entity("ApiTutoria2022_2.Models.Horario", b =>
                {
                    b.Property<int>("HorariosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoraFin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeccionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HorariosId");

                    b.ToTable("Horarios");

                    b.HasData(
                        new
                        {
                            HorariosId = 202,
                            Aula = "LAB. DE INFORMATICA A",
                            Dia = "Jueves",
                            HoraFin = "14:00",
                            HoraInicio = "12:00",
                            SeccionId = 202
                        },
                        new
                        {
                            HorariosId = 200,
                            Aula = "LAB. DE INFORMATICA A",
                            Dia = "Miercole",
                            HoraFin = "21:00",
                            HoraInicio = "18:00",
                            SeccionId = 200
                        },
                        new
                        {
                            HorariosId = 201,
                            Aula = "LAB. DE INFORMATICA B",
                            Dia = "Miercole",
                            HoraFin = "21:00",
                            HoraInicio = "18:00",
                            SeccionId = 201
                        },
                        new
                        {
                            HorariosId = 204,
                            Aula = "LAB. DE INFORMATICA C",
                            Dia = "Jueves",
                            HoraFin = "21:00",
                            HoraInicio = "18:00",
                            SeccionId = 204
                        });
                });

            modelBuilder.Entity("ApiTutoria2022_2.Models.Inscripcion", b =>
                {
                    b.Property<int>("InscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFinalTrimestre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicioTrimestre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistrada")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UltimaInscripcion")
                        .HasColumnType("INTEGER");

                    b.HasKey("InscripcionId");

                    b.ToTable("Inscripciones");

                    b.HasData(
                        new
                        {
                            InscripcionId = 104,
                            EstudianteId = 1,
                            FechaFinalTrimestre = new DateTime(2022, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicioTrimestre = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRegistrada = new DateTime(2022, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UltimaInscripcion = true
                        },
                        new
                        {
                            InscripcionId = 105,
                            EstudianteId = 2,
                            FechaFinalTrimestre = new DateTime(2022, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicioTrimestre = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRegistrada = new DateTime(2022, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UltimaInscripcion = true
                        },
                        new
                        {
                            InscripcionId = 106,
                            EstudianteId = 3,
                            FechaFinalTrimestre = new DateTime(2022, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicioTrimestre = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRegistrada = new DateTime(2022, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UltimaInscripcion = true
                        });
                });

            modelBuilder.Entity("ApiTutoria2022_2.Models.InscripcionDetalle", b =>
                {
                    b.Property<int>("InscripcionDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InscripcionDetalleId");

                    b.ToTable("InscripcionDetalles");

                    b.HasData(
                        new
                        {
                            InscripcionDetalleId = 90,
                            AsignaturaId = 20,
                            InscripcionId = 104
                        },
                        new
                        {
                            InscripcionDetalleId = 91,
                            AsignaturaId = 21,
                            InscripcionId = 104
                        },
                        new
                        {
                            InscripcionDetalleId = 92,
                            AsignaturaId = 22,
                            InscripcionId = 105
                        },
                        new
                        {
                            InscripcionDetalleId = 93,
                            AsignaturaId = 23,
                            InscripcionId = 105
                        },
                        new
                        {
                            InscripcionDetalleId = 94,
                            AsignaturaId = 23,
                            InscripcionId = 106
                        },
                        new
                        {
                            InscripcionDetalleId = 95,
                            AsignaturaId = 20,
                            InscripcionId = 106
                        });
                });

            modelBuilder.Entity("ApiTutoria2022_2.Models.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginId");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            LoginId = 1,
                            EstudianteId = 1,
                            Password = "1234",
                            Usuario = "Jesus"
                        },
                        new
                        {
                            LoginId = 2,
                            EstudianteId = 2,
                            Password = "1234",
                            Usuario = "2016"
                        },
                        new
                        {
                            LoginId = 3,
                            EstudianteId = 3,
                            Password = "1234",
                            Usuario = "5"
                        });
                });

            modelBuilder.Entity("ApiTutoria2022_2.Models.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoInstitucion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoPersonal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DireccionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<char>("Sexo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            Apellidos = "",
                            Celular = "",
                            CorreoInstitucion = "",
                            CorreoPersonal = "",
                            DireccionId = 0,
                            FechaNacimiento = new DateTime(2022, 7, 10, 22, 36, 41, 904, DateTimeKind.Local).AddTicks(6119),
                            Nacionalidad = "",
                            Nombres = "Enmanuel",
                            NumeroCedula = "",
                            Sexo = 'N',
                            Telefono = ""
                        },
                        new
                        {
                            PersonaId = 2,
                            Apellidos = "Abreu",
                            Celular = "",
                            CorreoInstitucion = "",
                            CorreoPersonal = "",
                            DireccionId = 0,
                            FechaNacimiento = new DateTime(2022, 7, 10, 22, 36, 41, 904, DateTimeKind.Local).AddTicks(6187),
                            Nacionalidad = "",
                            Nombres = "Jesus",
                            NumeroCedula = "",
                            Sexo = 'N',
                            Telefono = ""
                        },
                        new
                        {
                            PersonaId = 3,
                            Apellidos = "Peña Polonia",
                            Celular = "",
                            CorreoInstitucion = "",
                            CorreoPersonal = "",
                            DireccionId = 0,
                            FechaNacimiento = new DateTime(2022, 7, 10, 22, 36, 41, 904, DateTimeKind.Local).AddTicks(6212),
                            Nacionalidad = "",
                            Nombres = "Mario",
                            NumeroCedula = "",
                            Sexo = 'N',
                            Telefono = ""
                        });
                });

            modelBuilder.Entity("ApiTutoria2022_2.Models.Seccion", b =>
                {
                    b.Property<int>("SeccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeccionId");

                    b.ToTable("Secciones");

                    b.HasData(
                        new
                        {
                            SeccionId = 200,
                            AsignaturaId = 20,
                            DocenteId = 512
                        },
                        new
                        {
                            SeccionId = 201,
                            AsignaturaId = 21,
                            DocenteId = 512
                        },
                        new
                        {
                            SeccionId = 202,
                            AsignaturaId = 23,
                            DocenteId = 1
                        },
                        new
                        {
                            SeccionId = 204,
                            AsignaturaId = 22,
                            DocenteId = 514
                        });
                });

            modelBuilder.Entity("Asignatura", b =>
                {
                    b.Property<int>("AsignaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarreraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Credito")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AsignaturaId");

                    b.ToTable("Asignaturas");

                    b.HasData(
                        new
                        {
                            AsignaturaId = 20,
                            CarreraId = 12,
                            Codigo = "ISC-101",
                            Credito = 2,
                            Nombre = "PROGRAMACION APLICADA II"
                        },
                        new
                        {
                            AsignaturaId = 21,
                            CarreraId = 12,
                            Codigo = "ISC-102",
                            Credito = 1,
                            Nombre = "LAB. PROGRAM. APLICADA II"
                        },
                        new
                        {
                            AsignaturaId = 22,
                            CarreraId = 12,
                            Codigo = "ISC-802",
                            Credito = 4,
                            Nombre = "DISEÑO DE SISTEMAS"
                        },
                        new
                        {
                            AsignaturaId = 23,
                            CarreraId = 12,
                            Codigo = "ISC-116",
                            Credito = 4,
                            Nombre = "MERCADEO DE SOFTWARE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
